# Generated by Django 5.2.9 on 2025-12-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.CharField(blank=True, max_length=32, null=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hardware Key',
                'verbose_name_plural': 'Hardware Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=32, unique=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('package_filename', models.CharField(max_length=256)),
                ('package_hash', models.CharField(help_text='SHA-512 hash', max_length=128)),
                ('package_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('changelog', models.TextField(blank=True, null=True)),
                ('min_version', models.CharField(blank=True, help_text='Minimum version required to upgrade', max_length=32, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_seed', models.TextField(help_text='GPG-encrypted, base64-encoded')),
                ('key_fingerprints', models.TextField(help_text='JSON array of fingerprints')),
                ('salt', models.CharField(help_text='Base64-encoded salt', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('device', models.ForeignKey(db_column='device_id_hash', on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='api.device', to_field='device_id_hash')),
            ],
            options={
                'verbose_name': 'Seed',
                'verbose_name_plural': 'Seeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_value', models.CharField(max_length=128)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error')], max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('device', models.ForeignKey(db_column='device_id_hash', on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='api.device', to_field='device_id_hash')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
